# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'database_schema::flyway_cmd_placeholders') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    raise Puppet::ParseError, "flyway_cmd_placeholders argument must be a hash" unless args[0].is_a?(Hash)

    placeholders = Array.new
    args[0].each do |k,v|
      raise Puppet::ParseError, "flyway_cmd_placeholders hash keys must be strings"   unless k.is_a?(String)
      raise Puppet::ParseError, "flyway_cmd_placeholders hash values must be strings" unless v.is_a?(String)
      placeholders << "-placeholders.#{k}='#{v}'"
    end

    output = placeholders.join(' ')
  
  end
end
